spring:

  ##
  # default freemarker config
  ##
  freemarker:
    enabled: true
    charset: UTF-8
    cache: false
    check-template-location: true
    prefer-file-system-access: false
    template-loader-path:
      - classpath:/templates/

  ##
  # default jpa config
  ##
  jpa:
    open-in-view: true

  ##
  # default mail config
  ##
  mail:
    default-encoding: UTF-8
    protocol: smtp
    test-connection: true
    properties:
      mail.smtp.ssl.enable: true
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000
