# https://docs.github.com/en/github/administering-a-repository/keeping-your-dependencies-updated-automatically
version: 2
updates:

  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'latest'
    schedule:
      interval: 'daily'
      timezone: "Asia/Shanghai"
      time: '09:00'

  - package-ecosystem: 'gradle'
    directory: '/'
    target-branch: 'latest'
    schedule:
      interval: 'daily'
      timezone: "Asia/Shanghai"
      time: '09:00'