name: build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['java']

    steps:

    - name: checkout repository
      uses: actions/checkout@v2.3.2

    - name: cache gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
           ${{ runner.os }}-gradle-

    - name: inititalize codeql
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql/codeql-config.yml

    - name: gradle build
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: |
        chmod +x gradlew
        gradle build test

    - name: codeql analysis
      uses: github/codeql-action/analyze@v1

    - name: setup .net env
      uses: actions/setup-dotnet@v1.7.0
      with:
        dotnet-version: 3.1.401

    - name: report generator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.6.7
      with:
        reports: ./spring-oxygen-boot-starter/build/jacocoReport/test/jacocoTestReport.xml;./spring-oxygen-core/build/jacocoReport/test/jacocoTestReport.xml;./spring-oxygen-flysql/build/jacocoReport/test/jacocoTestReport.xml;./spring-oxygen-freecode/build/jacocoReport/test/jacocoTestReport.xml;./spring-oxygen-wechatgo/build/jacocoReport/test/jacocoTestReport.xml;
        targetdir: ./coverage/
        reporttypes: lcov
        sourcedirs: ./spring-oxygen-boot-starter/src/main/java/;./spring-oxygen-core/src/main/java/;./spring-oxygen-flysql/src/main/java/;./spring-oxygen-freecode/src/main/java/;./spring-oxygen-wechatgo/src/main/java/;

    - name: coveralls analysis
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}