name: 🔖 release for sonatype

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'which branch'
        required: true
      version:
        description: 'version number'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 11

    steps:
    - name: checkout repository
      uses: actions/checkout@v3.0.2
      with:
        ref: ${{ github.event.inputs.branch }}

    - name: cache gradle
      uses: actions/cache@v3.0.8
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: gradle build
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - run: |
        echo 'project.version=${{ github.event.inputs.version }}' >> gradle.properties
        ./gradlew build -x test

    - name: publish to sonatype
      run: |
        echo 'sonatypePassword=${{ secrets.SONATYPE_PASSWORD }}' >> gradle.properties
        ./gradlew publishMavenJavaPublicationToSonatypeRepository
