name: 🔖 release for github

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'which version like 0.0.x'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java:
          - 11

    steps:

    - name: checkout repository
      uses: actions/checkout@v2.3.4

    - name: cache gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: gradle build
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: |
        echo 'project.version=${{ github.event.inputs.version }}' >> gradle.properties
        gradle build -x test

    - name: publish to github
      run: |
        echo 'gpr.user=${{ secrets.GITHUB_USERNAME }}' >> gradle.properties
        echo 'gpr.key=${{ secrets.GITHUB_TOKEN }}' >> gradle.properties
        gradle publishGprPublicationToGitHubPackagesRepository