name: 🔖 release for github

on:
  workflow_dispatch:
    inputs:
      sure:
        description: 'are you sure release to github repository'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2.3.4

    - name: cache gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: gradle build
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: gradle build -x test

    - name: publish to github
      run: |
        echo 'gpr.user=${{ github.actor }}' >> gradle.properties
        echo 'gpr.key=${{ secrets.GITHUB_TOKEN }}' >> gradle.properties
        gradle publishGprPublicationToGitHubPackagesRepository